# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ea308337913c10958c0f3d5496dd8acca3604e5f819b59e4e883e900110b2960731c3dc8777afcdb1bd3b40df0f5595198454cccc6ec60c2c414b2d33aba4ec

test:
  secret_key_base: f1606484c28e669e2368b6956f03922e617862b4f3724ee3e6cb654d1cf97a518fcdea5e2db101761921e23e52ef1a1e4838b92ca8f1e7a46764e695133451d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
